# Generated by Django 2.1.7 on 2019-03-03 16:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Anfangsdatum')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Enddatum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
            ],
            options={
                'verbose_name': 'Periode',
                'verbose_name_plural': 'Perioden',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('duration', models.DurationField(default=datetime.timedelta(days=365), verbose_name='Laufzeit')),
                ('price', models.PositiveIntegerField(verbose_name='Preis')),
                ('mode', models.CharField(choices=[('auto', 'Automatisch'), ('manual', 'Manuell')], default='auto', max_length=6, verbose_name='Verwaltungsmodus')),
                ('is_purchasable', models.BooleanField(default=True, verbose_name='Käuflich')),
                ('is_renewable', models.BooleanField(default=True, verbose_name='Erneuerbar')),
                ('eligible_active_subscriptions_per_user', models.PositiveIntegerField(blank=True, default=None, help_text='Kein Wert bedeutet, dass es keine Begrenzung gibt.', null=True, verbose_name='Anzahl aktiver Abos pro Leserin')),
                ('eligible_email_domains', models.TextField(blank=True, default=None, help_text='E-Mail-Adressen müssen mit einem Semikolon getrennt sein.', verbose_name='Berechtigte E-Mail-Domains')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('renews_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscription.Plan', verbose_name='Erneuert als')),
            ],
            options={
                'verbose_name': 'Abotyp',
                'verbose_name_plural': 'Abotypen',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=150, verbose_name='Nachname')),
                ('address_line', models.CharField(max_length=100, verbose_name='Adresse')),
                ('additional_address_line', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adresszusatz')),
                ('postcode', models.CharField(max_length=8, verbose_name='Postleitzahl')),
                ('town', models.CharField(max_length=100, verbose_name='Ort')),
                ('country', models.CharField(default='Schweiz', max_length=50, verbose_name='Land')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Gekündigt am')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscription.Plan', verbose_name='Abotyp')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Abo',
                'verbose_name_plural': 'Abos',
            },
        ),
        migrations.AddField(
            model_name='period',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.Subscription', verbose_name='Abonnement'),
        ),
    ]
