# Generated by Django 2.1.1 on 2018-10-02 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('duration', models.PositiveSmallIntegerField(default=12, help_text='Laufzeit in Monaten', verbose_name='Laufzeit')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Preis')),
            ],
            options={
                'verbose_name': 'Abo-Typ',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=50, verbose_name='Adresse')),
                ('address_line_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adresszusatz')),
                ('postcode', models.CharField(max_length=8, verbose_name='Postleitzahl')),
                ('city', models.CharField(max_length=50, verbose_name='Ort')),
                ('country', models.CharField(default='Schweiz', max_length=50, verbose_name='Land')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('canceled_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscription.Plan', verbose_name='Abo-Typ')),
            ],
            options={
                'verbose_name': 'Abonnement',
            },
        ),
    ]
