# Generated by Django 2.1.7 on 2019-03-03 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Erstellt am'),
        ),
    ]
