# Generated by Django 2.1.7 on 2019-03-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20190303_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='eligible_email_domains',
            field=models.TextField(blank=True, default='', help_text='E-Mail-Adressen müssen mit einem Semikolon getrennt sein.', verbose_name='Berechtigte E-Mail-Domains'),
        ),
    ]
