# Generated by Django 2.1.4 on 2018-12-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_auto_20181116_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='email_domains',
            field=models.CharField(blank=True, help_text='Getrennt mit Semikolon', max_length=1000, null=True, verbose_name='Berechtigte E-Mail-Domains'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Preis'),
        ),
    ]
