# Generated by Django 2.1.4 on 2018-12-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_auto_20181208_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='email_domains',
        ),
        migrations.AddField(
            model_name='plan',
            name='amount_per_user',
            field=models.PositiveSmallIntegerField(default=0, help_text='Der Wert 0 bedeutet, dass es keine Begrenzung gibt.', verbose_name='Anzahl pro Leserin'),
        ),
        migrations.AddField(
            model_name='plan',
            name='eligible_email_domains',
            field=models.CharField(blank=True, help_text='E-Mail-Adressen müssen mit einem Semikolon getrennt sein.', max_length=1000, null=True, verbose_name='Berechtigte E-Mail-Domains'),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Dieser Wert bestimmt, ob das Abo gekauft oder verlängert werden kann.', verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.PositiveSmallIntegerField(default=12, help_text='Die Laufzeit muss in Monaten angegeben sein.', verbose_name='Laufzeit'),
        ),
    ]
