# Generated by Django 2.1.4 on 2018-12-09 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_auto_20181208_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('amount', models.PositiveIntegerField(verbose_name='Betrag')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Bezahlt am')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Periode',
                'verbose_name_plural': 'Perioden',
            },
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Abo'},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='amount_per_user',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='start_date',
        ),
        migrations.AddField(
            model_name='plan',
            name='active_subscriptions_per_user',
            field=models.PositiveIntegerField(default=0, help_text='Der Wert 0 bedeutet, dass es keine Begrenzung gibt.', verbose_name='Anzahl aktiver Abos pro Leserin'),
        ),
        migrations.AddField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.PositiveIntegerField(default=12, help_text='Die Laufzeit muss in Monaten angegeben sein.', verbose_name='Laufzeit'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='eligible_email_domains',
            field=models.TextField(blank=True, help_text='E-Mail-Adressen müssen mit einem Semikolon getrennt sein.', null=True, verbose_name='Berechtigte E-Mail-Domains'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Dieser Wert bestimmt, ob das Abo gekauft oder verlängert werden kann.', verbose_name='Ist aktiv'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='period',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.Subscription', verbose_name='Abonnement'),
        ),
    ]
