# Generated by Django 2.1.4 on 2018-12-09 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_auto_20181209_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='active_subscriptions_per_user',
            new_name='max_active_subscriptions_per_user',
        ),
    ]
