# Generated by Django 2.1.4 on 2018-12-09 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_auto_20181209_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'Abotyp', 'verbose_name_plural': 'Abotypen'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Abo', 'verbose_name_plural': 'Abos'},
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_active_subscriptions_per_user',
            field=models.PositiveIntegerField(blank=True, help_text='Kein Wert bedeutet, dass es keine Begrenzung gibt.', null=True, verbose_name='Anzahl aktiver Abos pro Leserin'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscription.Plan', verbose_name='Abotyp'),
        ),
    ]
