# Generated by Django 2.1.1 on 2018-10-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Betrag')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('paid_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Bezahlt am')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zahlung',
                'verbose_name_plural': 'Zahlungen',
            },
        ),
    ]
