# Generated by Django 2.1.7 on 2019-03-03 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Betrag')),
                ('method', models.CharField(choices=[('invoice', 'Rechnung'), ('twint', 'Twint')], max_length=20, verbose_name='Zahlungsmethode')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('paid_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Bezahlter Betrag')),
                ('paid_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Bezahlt am')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subscription.Period', verbose_name='Abo')),
            ],
            options={
                'verbose_name': 'Zahlung',
                'verbose_name_plural': 'Zahlungen',
            },
        ),
    ]
