# Generated by Django 3.0.3 on 2020-02-19 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Betrag in Schweizer Franken')),
                ('method', models.CharField(choices=[('invoice', 'Banküberweisung')], default='invoice', max_length=20, verbose_name='Zahlungsmethode')),
                ('due_on', models.DateField(verbose_name='Zahlbar bis')),
                ('paid_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Bezahlt am')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Erstellt am')),
            ],
            options={
                'verbose_name': 'Zahlung',
                'verbose_name_plural': 'Zahlungen',
            },
        ),
    ]
