# Generated by Django 3.0.3 on 2020-02-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Betrag in Schweizer Franken'),
        ),
    ]
