# Generated by Django 3.0.3 on 2020-02-19 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20200218_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='code',
        ),
    ]
