# Generated by Django 2.1.7 on 2019-03-03 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('signup', 'Bestätigungs-Token'), ('login', 'Login-Token')], max_length=6, verbose_name='Typ')),
                ('code', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Code')),
                ('valid_until', models.DateTimeField(verbose_name='gültig bis')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='gesendet am')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Abonnentin')),
            ],
            options={
                'verbose_name': 'Token',
            },
        ),
    ]
