# Generated by Django 2.1.1 on 2018-10-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('signup', 'Bestätigungs-Token'), ('login', 'Login-Token')], max_length=6, verbose_name='Typ')),
                ('code', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Code')),
                ('valid_until', models.DateTimeField(verbose_name='gültig bis')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='gesendet am')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Token',
            },
        ),
    ]
